#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[4]
SRC = ROOT / "src" / "display_ui" / "dashboard_font.rs"
FONT_PATH = Path("/System/Library/Fonts/Supplemental/Arial Narrow Bold.ttf")
CHARSET = " 0123456789.-/ABCDEFGHIJKLMNOPQRSTUVWXYZ"

FONTS = [
    ("SMALL", 16, 2, 2),
    ("MEDIUM", 30, 2, 3),
    ("LARGE", 48, 2, 3),
]


def render_font(size: int, pad_x: int, pad_y: int):
    font = ImageFont.truetype(str(FONT_PATH), size=size)
    boxes = {}
    min_top = 10**9
    max_bottom = -10**9
    drawer = ImageDraw.Draw(Image.new("L", (1, 1), 0))
    for ch in CHARSET:
        bbox = drawer.textbbox((0, 0), ch, font=font)
        boxes[ch] = bbox
        min_top = min(min_top, bbox[1])
        max_bottom = max(max_bottom, bbox[3])

    line_h = max_bottom - min_top + pad_y * 2
    glyphs = []
    for ch in CHARSET:
        bbox = boxes[ch]
        glyph_w = max(1, bbox[2] - bbox[0])
        glyph_h = max(1, bbox[3] - bbox[1])
        img = Image.new("L", (glyph_w, glyph_h), 0)
        d = ImageDraw.Draw(img)
        x = -bbox[0]
        y = -bbox[1]
        d.text((x, y), ch, font=font, fill=255)
        advance = round(drawer.textlength(ch, font=font))
        y_offset = pad_y + bbox[1] - min_top
        glyphs.append((ch, glyph_w, glyph_h, advance, y_offset, list(img.tobytes())))
    return line_h, glyphs


def rust_array(values, indent="            "):
    chunks = []
    line = []
    for i, value in enumerate(values, 1):
        line.append(f"{value:3d}")
        if i % 16 == 0:
            chunks.append(indent + ", ".join(line) + ",")
            line = []
    if line:
        chunks.append(indent + ", ".join(line) + ",")
    return "\n".join(chunks)


def main():
    if not FONT_PATH.exists():
        raise FileNotFoundError(FONT_PATH)

    out = []
    out.append("// @generated by docs/specs/3j4df-gc9307-shell-dashboard-ui/tools/generate_dashboard_font.py")
    out.append("// Source font: /System/Library/Fonts/Supplemental/Arial Narrow Bold.ttf")
    out.append("")
    out.append("pub struct AaGlyph {")
    out.append("    pub ch: u8,")
    out.append("    pub width: u8,")
    out.append("    pub height: u8,")
    out.append("    pub advance: u8,")
    out.append("    pub y_offset: u8,")
    out.append("    pub alpha: &'static [u8],")
    out.append("}")
    out.append("")
    out.append("pub struct AaFont {")
    out.append("    pub line_h: u8,")
    out.append("    pub glyphs: &'static [AaGlyph],")
    out.append("}")
    out.append("")
    out.append("pub fn lookup_glyph(font: &'static AaFont, ch: u8) -> &'static AaGlyph {")
    out.append("    for glyph in font.glyphs {")
    out.append("        if glyph.ch == ch {")
    out.append("            return glyph;")
    out.append("        }")
    out.append("    }")
    out.append("    for glyph in font.glyphs {")
    out.append("        if glyph.ch == b'?' {")
    out.append("            return glyph;")
    out.append("        }")
    out.append("    }")
    out.append("    &font.glyphs[0]")
    out.append("}")
    out.append("")

    for name, size, pad_x, pad_y in FONTS:
        line_h, glyphs = render_font(size, pad_x, pad_y)
        out.append(f"pub const {name}: AaFont = AaFont {{")
        out.append(f"    line_h: {line_h},")
        out.append(f"    glyphs: &{name}_GLYPHS,")
        out.append("};")
        out.append("")
        out.append(f"static {name}_GLYPHS: [AaGlyph; {len(glyphs)}] = [")
        for ch, glyph_w, glyph_h, advance, y_offset, data in glyphs:
            out.append("    AaGlyph {")
            out.append(f"        ch: {ch.encode('ascii')[0]},")
            out.append(f"        width: {glyph_w},")
            out.append(f"        height: {glyph_h},")
            out.append(f"        advance: {advance},")
            out.append(f"        y_offset: {y_offset},")
            out.append("        alpha: &[")
            out.append(rust_array(data))
            out.append("        ],")
            out.append("    },")
        out.append("];")
        out.append("")

    SRC.write_text("\n".join(out) + "\n")
    print(SRC)


if __name__ == "__main__":
    main()
